apiVersion: v1
kind: Secret
metadata:
    name: steadystate-backup-store
    namespace: cnpg-system
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:vmXaDiJqvCV2fd+uwUlkMTcN15HwSkIQ1vkKKh+Zb2lNmZ9x41wyWAImOlDMB8GN,iv:MqvXkotsQ0u+/0tEtHp44OFl/r/KfImDidcrsZhXJVQ=,tag:GSPyWf316g+ODxJMb+Y+jg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:karGPFkBjf/bDfJCRcDCQhXs13VAQcAfLNktL9XAaEi5OWNqwOmmeJXwTN9MDGdHXRZvEDvaW1dSzh0I46DXe5Fo6seilfmE,iv:gV2AqHGgYBPdUkfBnzxxcJ+/7SNqjy/VUPFtKJW0hkk=,tag:Bx++exb9ZL7ci9e8iMPNtg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1L21EZzREREQzK2pVQWFL
            VG5lSzU3VkV0cUU1aVhaTklSdU1tZGZrbVdFCnpXTlk3MFdvb0hNWnd0YTdXK3NU
            U05wMGsyK1RnMUZ4VjlxUlVUS3RsWXcKLS0tIGptSkdzdG5uQWIvbnNLSjk1UEpz
            S29jMHJMWjUwa3g0WGRNRHA4R0N0dW8KsCnIGkE4gEo8CbXwn5FhBdlqGnvCBplV
            YoIbT1hvYVibSTnynKlNh3r8jFXOse71oaYxKJBzzJ1M1gwA1EXp9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19nqqe30cjcegfagf63ccamqd9a2qw9vv6xavscjcldsz6u2mpf3sm6qs0p
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-26T12:43:16Z"
    mac: ENC[AES256_GCM,data:0oLl6ZFIpZTmuUS9F8M/cVZpRoSHVw3U7DntdT2pVG4M8qwmigu2NaBhIvxBGUiBWIYAR7sIltgPeybWHaR/c0FQ/fUPmtGayZx2boIDRBHPoHfnCm3Ob4YcfW0fXWpCt3h0XvHFWZij8siHNGbSyRgpBmD+SPGIyZ+XYSeT76s=,iv:F2h7L4BZfQMG8z7KvuyhTVO+AmBHQEVBRUdipkhPpu8=,tag:SrTgohLK+mqWVgFiyNzUuw==,type:str]
    version: 3.13.2
