apiVersion: v1
kind: Secret
metadata:
    name: steadystate-grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:a+meFW8=,iv:s3uoepzkZBhGFQ7EkqTe6W4eq28j0hdCoS/aVxjoPrM=,tag:zmoVc38DFDshJdzrZY5WEw==,type:str]
    admin-password: ENC[AES256_GCM,data:LunMNSy4WUdpPh7HRK9oh5Af9AfBU1m3S1xPFLLh1cd6bpOVSOu0OZssh/I=,iv:XyrAIFr0Kolsy2nxxl4ksEinbxJCyC24894HOoCXfTg=,tag:7EaQumNEjedff7PPZUGq9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubE1oVVdLTmJQR2pDSmRD
            RDJwT2hoVklUb0dHb3BnalhobXBTOWcvTWcwCnBhZ3cxSllLck0yRW15NVpWTVI0
            eTIzSUV3ODJLRzRTVHVGNGI3dlFxVDQKLS0tIEp2cGhXLy9mOUdLLzlFaWlZamlq
            OGNEeVRJKzVPM2FKaGU1T2NmaDBad3MKgaxbwNtuRJBoc/sSYcTwR4oaVm3zLNia
            Ek+5ELGk39oLaUOBBHXava3ui7vklkU+abuTXqeI7cjvF1sas8txng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19nqqe30cjcegfagf63ccamqd9a2qw9vv6xavscjcldsz6u2mpf3sm6qs0p
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T09:39:34Z"
    mac: ENC[AES256_GCM,data:L407sDOg/suytlg2KUbzrR3LQstYL7+ldU3YxPHnZCHq1FhclRFghgHolsoTLxAYGrXA+Id3Us3EE3h3GdqXl3yfxL+7FrVWjTpiq6flja/PDXawLwZfb2zcZwEQ6gAl8hjwWw2MBJbiK1zgw5pobpdl9TllQO4hDArvZCZ95iw=,iv:FySfXpAE5qiieMv7tVRWtPmfAb9x8wDxWSDWAdAHtvE=,tag:mmd2Q9hzV3wE/EvKlzBc7A==,type:str]
    version: 3.13.2
