---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: manager
          image: ghcr.io/saadabdullaah/steadystate-operator:v0.1.0
          imagePullPolicy: IfNotPresent
          command: ["/manager"]
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=0
          ports:
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
            runAsNonRoot: true
