apiVersion: cli.steadystate.dev/v1alpha1
components:
- application: xyz
  dockerfile: web/Dockerfile
  name: web
  path: web
  port: 8080
  runtime: react-go
- application: xyz-api
  dockerfile: api/Dockerfile
  name: api
  path: api
  port: 8080
  runtime: go
kind: ServiceDescriptor
name: xyz
template: full-stack
version: v0.1.1
