defaultRules:
  create: false

alertmanager:
  enabled: true
  config:
    route:
      receiver: "null"
    receivers:
      - name: "null"
  alertmanagerSpec:
    replicas: 1
    retention: 6h
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

grafana:
  enabled: true
  defaultDashboardsEnabled: false
  env:
    GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
  grafana.ini:
    auth:
      disable_login_form: true
    auth.anonymous:
      enabled: true
      org_role: Viewer
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

kubeApiServer:
  enabled: false
kubelet:
  enabled: true
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: false
prometheus-node-exporter:
  enabled: false

kube-state-metrics:
  collectors:
    - pods
  metricLabelsAllowlist:
    - pods=[app.kubernetes.io/instance,app.kubernetes.io/managed-by,rollouts-pod-template-hash]
  resources:
    requests:
      cpu: 25m
      memory: 48Mi
    limits:
      cpu: 100m
      memory: 96Mi

prometheusOperator:
  admissionWebhooks:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 192Mi

prometheus:
  enabled: true
  prometheusSpec:
    replicas: 1
    retention: 6h
    scrapeInterval: 15s
    evaluationInterval: 15s
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    ruleNamespaceSelector: {}
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 768Mi
