apiVersion: platform.steadystate.dev/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    steadystate.dev/deletion-request: c6d3ba59-87bd-4189-84f5-c2ca00578f7d
  name: xyz-api
  namespace: team-xyz
spec:
  deployment:
    automaticRollback: true
    steps:
    - pause: 30s
      weight: 10
    - pause: 30s
      weight: 25
    - pause: 30s
      weight: 50
    - pause: 30s
      weight: 100
    strategy: canary
  image:
    repository: ghcr.io/saadabdullaah/steadystate-services
    tag: xyz-api-v0.1.2
  observability:
    logs: true
    metrics: true
    traces: true
  owner: xyz-owners
  reliability:
    availabilityTarget: 99.9%
    maximumErrorRate: 1%
    maximumP95Latency: 250ms
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 32Mi
  runtime:
    port: 8080
    replicas:
      max: 3
      min: 1
  security:
    networkIsolation: false
    requireSignedImage: true
    runAsNonRoot: true
