repoURL: https://github.com/saadabdullaah/steadystate.git
gitRevision: main
bootstrapRoot: false
rootTargetRevision: main
enableTelemetryPipeline: true
enableSecurity: true
enableProgressiveDelivery: true
enableDataFoundation: false
enableTenantWorkloads: true
tenantFilter: ""
monitoringKubeStateMetricsEnabled: true
backupStoreEndpoint: http://172.30.240.10:8333
operatorImage: ghcr.io/saadabdullaah/steadystate-operator:v0.3.0
argoRolloutsChartVersion: 2.41.0
kubePrometheusStackChartVersion: 87.16.1
lokiChartVersion: 18.5.1
alloyChartVersion: 1.10.1
tempoChartVersion: 1.24.4
otelCollectorChartVersion: 0.165.0
kyvernoChartVersion: 3.8.2
certManagerChartVersion: v1.21.0
cloudNativePGChartVersion: 0.29.0
barmanCloudChartVersion: 0.7.0
