resources:
- application_admin_role.yaml
- application_editor_role.yaml
- application_viewer_role.yaml
- team_admin_role.yaml
- team_editor_role.yaml
- team_viewer_role.yaml
- team_owner_role.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- manager_role_binding.yaml
- role.yaml
