apiVersion: platform.steadystate.dev/v1alpha1
kind: Team
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    steadystate.dev/deletion-request: 944e63d2-eefb-4b3f-9e5c-3fc598187606
  name: xyz
spec:
  allowedRepositories:
  - ghcr.io/saadabdullaah/steadystate-services
  owners:
  - xyz-owners
  quota:
    cpu: "2"
    memory: 4Gi
