apiVersion: platform.steadystate.dev/v1alpha1
kind: Team
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    steadystate.dev/deletion-request: 4331114a-3977-4924-a8bd-a52cc6e1ab85
  name: xyz
spec:
  allowedRepositories:
  - ghcr.io/saadabdullaah/steadystate-services
  owners:
  - xyz-owners
  quota:
    cpu: "2"
    memory: 4Gi
