apiVersion: cli.steadystate.dev/v1alpha1
kind: TenantCatalog
tenants:
- applications:
  - databaseRef: orders
    lifecycle: Active
    name: demo
    path: gitops/applications/demo
  databases:
  - lifecycle: Active
    name: orders
    path: gitops/databases/orders
  lifecycle: Active
  name: payments
  owners:
  - payments-owner
  services: []
  teamPath: gitops/teams/payments
- applications:
  - lifecycle: Active
    name: xyz
    path: gitops/applications/xyz
  - databaseRef: xyz
    lifecycle: Active
    name: xyz-api
    path: gitops/applications/xyz-api
  databases:
  - lifecycle: Active
    name: xyz
    path: gitops/databases/xyz
  lifecycle: Active
  name: xyz
  owners:
  - xyz-owners
  services:
  - components:
    - xyz
    - xyz-api
    databaseRef: xyz
    lifecycle: Active
    name: xyz
    ownsDatabase: true
    ownsTeam: true
    path: services/xyz
    template: full-stack
    version: v0.1.1
  teamPath: gitops/teams/xyz
- applications: []
  databases: []
  lifecycle: Active
  name: portal-smoke-31888881140-1
  owners:
  - platform-team
  services: null
  teamPath: gitops/teams/portal-smoke-31888881140-1
