fullnameOverride: loki
deploymentMode: Monolithic

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
  storage:
    type: filesystem
  limits_config:
    retention_period: 24h
  compactor:
    retention_enabled: true
    delete_request_store: filesystem

singleBinary:
  replicas: 1
  affinity: {}
  podDisruptionBudget:
    enabled: false
  persistence:
    enabled: false
    dataVolumeParameters:
      emptyDir:
        sizeLimit: 4Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

gateway:
  enabled: false
lokiCanary:
  enabled: false
test:
  enabled: false
chunksCache:
  enabled: false
resultsCache:
  enabled: false
minio:
  enabled: false
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
