apiVersion: platform.steadystate.dev/v1alpha1
kind: Database
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    steadystate.dev/deletion-request: c13b8aef-f1f7-4d2e-91f9-0269a09b3600
  name: xyz
  namespace: team-xyz
spec:
  backups:
    enabled: true
    retention: 7d
    schedule: 0 0 2 * * *
  engine: postgres
  instances: 1
  storage:
    size: 1Gi
    storageClassName: local-path
