apiVersion: platform.steadystate.dev/v1alpha1
kind: Database
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    steadystate.dev/deletion-request: df750bfe-dfb2-42f7-9f91-5deff8a8c063
  name: xyz
  namespace: team-xyz
spec:
  backups:
    enabled: true
    retention: 7d
    schedule: 0 0 2 * * *
  engine: postgres
  instances: 1
  storage:
    size: 1Gi
    storageClassName: local-path
