apiVersion: platform.steadystate.dev/v1alpha1
kind: Database
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    steadystate.dev/deletion-request: c6d3ba59-87bd-4189-84f5-c2ca00578f7d
  name: xyz
  namespace: team-xyz
spec:
  backups:
    enabled: true
    retention: 7d
    schedule: 0 0 2 * * *
  engine: postgres
  instances: 1
  storage:
    size: 1Gi
    storageClassName: local-path
