apiVersion: platform.steadystate.dev/v1alpha1
kind: Database
metadata:
  name: orders
  namespace: team-payments
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Prune=false
spec:
  engine: postgres
  instances: 1
  storage:
    size: 1Gi
    storageClassName: local-path
  backups:
    enabled: true
    schedule: "0 0 2 * * *"
    retention: 7d
