package platformctl

import (
	_ "embed"
	"fmt"
	"go/format"
	"io/fs"
	"sort"
	"strings"

	"sigs.k8s.io/yaml"
)

const serviceImageRepository = "ghcr.io/saadabdullaah/steadystate-services"

//go:embed templates/react-package-lock.json
var reactPackageLock string

type serviceDescriptor struct {
	APIVersion string                       `json:"apiVersion" yaml:"apiVersion"`
	Kind       string                       `json:"kind" yaml:"kind"`
	Name       string                       `json:"name" yaml:"name"`
	Template   string                       `json:"template" yaml:"template"`
	Version    string                       `json:"version" yaml:"version"`
	Components []serviceDescriptorComponent `json:"components" yaml:"components"`
}

type serviceDescriptorComponent struct {
	Name        string `json:"name" yaml:"name"`
	Application string `json:"application" yaml:"application"`
	Path        string `json:"path" yaml:"path"`
	Runtime     string `json:"runtime" yaml:"runtime"`
	Port        int    `json:"port" yaml:"port"`
	Dockerfile  string `json:"dockerfile" yaml:"dockerfile"`
}

func (r *changeRenderer) writeServiceSource(service CatalogService) error {
	files, err := r.serviceFiles(service)
	if err != nil {
		return err
	}
	paths := make([]string, 0, len(files))
	for path := range files {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		if err := r.set(service.Path+"/"+path, files[path]); err != nil {
			return err
		}
	}
	return nil
}

func (r *changeRenderer) writeServiceVersion(service *CatalogService) error {
	if err := r.set(service.Path+"/VERSION", []byte(service.Version+"\n")); err != nil {
		return err
	}
	descriptor, err := serviceDescriptorFor(*service)
	if err != nil {
		return err
	}
	return r.set(service.Path+"/service.yaml", descriptor)
}

func (r *changeRenderer) deleteServiceSource(service CatalogService) error {
	expected, err := r.serviceFiles(service)
	if err != nil {
		return err
	}
	actual := []string{}
	err = fs.WalkDir(r.repository.FS(), service.Path, func(currentPath string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			return nil
		}
		relative := strings.TrimPrefix(currentPath, service.Path+"/")
		if relative == currentPath || relative == "" {
			return exitError(ExitConflict, "service source contains an invalid path %q", currentPath)
		}
		actual = append(actual, relative)
		return nil
	})
	if err != nil {
		return exitError(ExitConflict, "inspect service source: %v", err)
	}
	sort.Strings(actual)
	expectedPaths := make([]string, 0, len(expected))
	for path := range expected {
		expectedPaths = append(expectedPaths, path)
	}
	sort.Strings(expectedPaths)
	if strings.Join(actual, "\x00") != strings.Join(expectedPaths, "\x00") {
		return exitError(ExitConflict, "service %q contains files outside its generated template", service.Name)
	}
	for _, path := range actual {
		if err := r.remove(service.Path + "/" + path); err != nil {
			return err
		}
	}
	return nil
}

func (r *changeRenderer) serviceFiles(service CatalogService) (map[string][]byte, error) {
	descriptor, err := serviceDescriptorFor(service)
	if err != nil {
		return nil, err
	}
	files := map[string][]byte{
		"VERSION":      []byte(service.Version + "\n"),
		"service.yaml": descriptor,
		"README.md":    []byte(fmt.Sprintf("# %s\n\nGenerated by `platformctl` from the `%s` golden template.\n\nRun `platformctl dev %s` for the host-native development loop. Production changes are built, signed, attested, and activated through Git.\n", service.Name, service.Template, service.Name)),
	}
	if service.Template == "go-api" || service.Template == "full-stack" {
		component := "api"
		if service.Template == "go-api" {
			component = "api"
		}
		mainSource, readErr := r.repository.ReadFile("apps/demo-app/main.go")
		if readErr != nil {
			return nil, fmt.Errorf("read Go API golden source: %w", readErr)
		}
		testSource, readErr := r.repository.ReadFile("apps/demo-app/main_test.go")
		if readErr != nil {
			return nil, fmt.Errorf("read Go API golden tests: %w", readErr)
		}
		files[component+"/main.go"] = mainSource
		files[component+"/main_test.go"] = testSource
		files[component+"/Dockerfile"] = []byte(goAPIDockerfile(service.Name, component))
	}
	if service.Template == "react-static" || service.Template == "full-stack" {
		for path, content := range reactTemplateFiles(service.Name, service.Template == "full-stack") {
			files["web/"+path] = []byte(content)
		}
	}
	for path, content := range files {
		if !strings.HasSuffix(path, ".go") {
			continue
		}
		formatted, formatErr := format.Source(content)
		if formatErr != nil {
			return nil, fmt.Errorf("format generated Go source %s: %w", path, formatErr)
		}
		files[path] = formatted
	}
	return files, nil
}

func serviceDescriptorFor(service CatalogService) ([]byte, error) {
	components := []serviceDescriptorComponent{}
	if service.Template == "go-api" {
		components = append(components, serviceDescriptorComponent{Name: "api", Application: service.Name, Path: "api", Runtime: "go", Port: 8080, Dockerfile: "api/Dockerfile"})
	} else {
		components = append(components, serviceDescriptorComponent{Name: "web", Application: service.Name, Path: "web", Runtime: "react-go", Port: 8080, Dockerfile: "web/Dockerfile"})
		if service.Template == "full-stack" {
			components = append(components, serviceDescriptorComponent{Name: "api", Application: service.Name + "-api", Path: "api", Runtime: "go", Port: 8080, Dockerfile: "api/Dockerfile"})
		}
	}
	return yaml.Marshal(serviceDescriptor{APIVersion: "cli.steadystate.dev/v1alpha1", Kind: "ServiceDescriptor", Name: service.Name, Template: service.Template, Version: service.Version, Components: components})
}

func goAPIDockerfile(service, component string) string {
	return fmt.Sprintf(`ARG GO_BUILDER=golang:1.25.12-alpine3.23@sha256:cc985ef6f9c3bf9ece7488129c9abe0a150388ccdfa428d886fc709dca0b230a
FROM ${GO_BUILDER} AS builder
ARG TARGETARCH
WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download
COPY services/%s/%s ./services/%s/%s
RUN CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH} go build -buildvcs=false -trimpath -ldflags="-s -w" -o /out/service ./services/%s/%s
FROM scratch
USER 65532:65532
COPY --from=builder /out/service /service
ENTRYPOINT ["/service"]
`, service, component, service, component, service, component)
}

func reactTemplateFiles(name string, proxy bool) map[string]string {
	proxyTarget := ""
	if proxy {
		// The API Service exposes port 80 and forwards to the container's 8080
		// targetPort. In-cluster clients must address the Service port.
		proxyTarget = "http://" + name + "-api"
	}
	return map[string]string{
		"package.json":          fmt.Sprintf("{\n  \"name\": \"%s-web\",\n  \"private\": true,\n  \"version\": \"0.1.0\",\n  \"type\": \"module\",\n  \"scripts\": {\"build\": \"tsc -b && vite build\", \"dev\": \"vite --host 127.0.0.1\", \"test\": \"node --test test/*.test.js\"},\n  \"dependencies\": {\"@types/node\": \"24.13.3\", \"@types/react\": \"19.2.18\", \"@types/react-dom\": \"19.2.4\", \"@vitejs/plugin-react\": \"6.0.5\", \"vite\": \"8.1.5\", \"typescript\": \"7.0.2\", \"react\": \"19.2.8\", \"react-dom\": \"19.2.8\"},\n  \"devDependencies\": {}\n}\n", name),
		"package-lock.json":     strings.ReplaceAll(reactPackageLock, "steadystate-service-web", name+"-web"),
		"index.html":            "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>" + name + "</title></head><body><div id=\"root\"></div><script type=\"module\" src=\"/src/main.tsx\"></script></body></html>\n",
		"tsconfig.json":         "{\"compilerOptions\":{\"target\":\"ESNext\",\"lib\":[\"ESNext\",\"DOM\"],\"module\":\"ESNext\",\"moduleResolution\":\"Bundler\",\"types\":[\"node\",\"vite/client\"],\"jsx\":\"react-jsx\",\"strict\":true,\"noEmit\":true},\"include\":[\"src\",\"vite.config.ts\"]}\n",
		"vite.config.ts":        "import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\nexport default defineConfig({plugins:[react()],server:{proxy:{'/api':{target:'http://127.0.0.1:8081',changeOrigin:true,rewrite:p=>p.replace(/^\\/api/,'')}}}});\n",
		"src/main.tsx":          "import React from 'react';\nimport {createRoot} from 'react-dom/client';\nimport './style.css';\nfunction App(){return <main><p className=\"eyebrow\">STEADYSTATE SERVICE</p><h1>" + name + "</h1><p>Git-reviewed, observable, signed, and progressively delivered.</p></main>}\ncreateRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);\n",
		"src/style.css":         ":root{font-family:system-ui;color:#e8edf5;background:#10151d}body{margin:0;min-height:100vh;display:grid;place-items:center}main{max-width:44rem;padding:3rem}.eyebrow{color:#70d6a8;letter-spacing:.18em}h1{font-size:clamp(3rem,10vw,7rem);margin:.2em 0}\n",
		"test/template.test.js": "import test from 'node:test';\nimport assert from 'node:assert/strict';\nimport {readFile} from 'node:fs/promises';\ntest('golden page preserves runtime identity and API boundary',async()=>{const [page,source]=await Promise.all([readFile(new URL('../index.html',import.meta.url),'utf8'),readFile(new URL('../src/main.tsx',import.meta.url),'utf8')]);assert.match(page,/src\\/main\\.tsx/);assert.match(source,/STEADYSTATE SERVICE/);});\n",
		"server/main.go":        reactServerSource(name, proxyTarget),
		"server/main_test.go": `package main
import("net/http/httptest";"testing")
func TestHealth(t *testing.T){r:=httptest.NewRecorder(); newHandler("").ServeHTTP(r,httptest.NewRequest("GET","/healthz",nil)); if r.Code!=200{t.Fatalf("status %d",r.Code)}}
`,
		"server/static/index.html": "<!doctype html><html lang=\"en\"><body><main>Build the frontend before running the production server.</main></body></html>\n",
		"Dockerfile": fmt.Sprintf(`ARG NODE_IMAGE=node:24.17.0-alpine@sha256:156b55f92e98ccd5ef49578a8cea0df4679826564bad1c9d4ef04462b9f0ded6
ARG GO_BUILDER=golang:1.25.12-alpine3.23@sha256:cc985ef6f9c3bf9ece7488129c9abe0a150388ccdfa428d886fc709dca0b230a
FROM ${NODE_IMAGE} AS frontend
WORKDIR /src
COPY services/%s/web/package.json services/%s/web/package-lock.json ./
RUN npm ci
COPY services/%s/web ./
RUN npm run build
FROM ${GO_BUILDER} AS server
ARG TARGETARCH
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY services/%s/web/server ./services/%s/web/server
COPY --from=frontend /src/dist ./services/%s/web/server/static
RUN CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH} go build -buildvcs=false -trimpath -ldflags="-s -w" -o /out/web ./services/%s/web/server
FROM scratch
USER 65532:65532
COPY --from=server /out/web /web
ENTRYPOINT ["/web"]
`, name, name, name, name, name, name, name),
	}
}

func serviceImageTag(service CatalogService, application, version string) string {
	role := "web"
	if service.Template == "go-api" || application == service.Name+"-api" {
		role = "api"
	}
	return service.Name + "-" + role + "-" + version
}

func reactServerSource(name, proxyTarget string) string {
	return fmt.Sprintf(`package main
import(
 "context"
 "crypto/rand"
 "embed"
 "encoding/hex"
 "encoding/json"
 "io"
 "io/fs"
 "log/slog"
 "net/http"
 "net/http/httputil"
 "net/url"
 "os"
 "os/signal"
 "strconv"
 "strings"
 "sync/atomic"
 "syscall"
 "time"
 "go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
 "go.opentelemetry.io/otel"
 "go.opentelemetry.io/otel/attribute"
 "go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"
 "go.opentelemetry.io/otel/propagation"
 "go.opentelemetry.io/otel/sdk/resource"
 sdktrace "go.opentelemetry.io/otel/sdk/trace"
 "go.opentelemetry.io/otel/trace"
)
//go:embed static/*
var assets embed.FS
var requests atomic.Uint64
type statusWriter struct{http.ResponseWriter;status int}
func(w *statusWriter)WriteHeader(status int){w.status=status;w.ResponseWriter.WriteHeader(status)}
func main(){
 slog.SetDefault(slog.New(slog.NewJSONHandler(os.Stdout,nil)))
 ctx,stop:=signal.NotifyContext(context.Background(),os.Interrupt,syscall.SIGTERM);defer stop()
 shutdown,err:=configureTracing(ctx);if err!=nil{slog.Error("configure tracing","error",err);os.Exit(1)};defer func(){flush,cancel:=context.WithTimeout(context.Background(),10*time.Second);defer cancel();_ = shutdown(flush)}()
 server:=&http.Server{Addr:":8080",Handler:otelhttp.NewHandler(newHandler(%q),"http.server"),ReadHeaderTimeout:5*time.Second,ReadTimeout:15*time.Second,WriteTimeout:15*time.Second,IdleTimeout:30*time.Second}
 errors:=make(chan error,1);go func(){errors<-server.ListenAndServe()}();slog.Info("web listening","application",%q)
 select{case err:=<-errors:if err!=nil&&err!=http.ErrServerClosed{slog.Error("server stopped","error",err);os.Exit(1)};case <-ctx.Done():shutdownCtx,cancel:=context.WithTimeout(context.Background(),10*time.Second);defer cancel();if err:=server.Shutdown(shutdownCtx);err!=nil{slog.Error("graceful shutdown","error",err);os.Exit(1)}}
}
func newHandler(proxyTarget string)http.Handler{
 mux:=http.NewServeMux()
 mux.HandleFunc("/healthz",func(w http.ResponseWriter,_ *http.Request){w.WriteHeader(http.StatusOK)})
 mux.HandleFunc("/readyz",func(w http.ResponseWriter,_ *http.Request){w.WriteHeader(http.StatusOK)})
 mux.HandleFunc("/metrics",func(w http.ResponseWriter,_ *http.Request){w.Header().Set("Content-Type","text/plain; version=0.0.4");_,_=io.WriteString(w,"http_requests_total{application=\\\"%s\\\",namespace=\\\""+value("STEADYSTATE_APP_NAMESPACE","local")+"\\\",version=\\\""+value("STEADYSTATE_APP_VERSION","development")+"\\\",status=\\\"200\\\"} "+strconv.FormatUint(requests.Load(),10)+"\\n")})
 mux.HandleFunc("/.well-known/runtime",func(w http.ResponseWriter,_ *http.Request){w.Header().Set("Content-Type","application/json");_=json.NewEncoder(w).Encode(map[string]string{"application":%q,"namespace":value("STEADYSTATE_APP_NAMESPACE","local"),"version":value("STEADYSTATE_APP_VERSION","development")})})
 if proxyTarget!=""{target,_:=url.Parse(proxyTarget);proxy:=httputil.NewSingleHostReverseProxy(target);mux.Handle("/api/",http.StripPrefix("/api",proxy))}
 built,_:=fs.Sub(assets,"static");files:=http.FileServer(http.FS(built));mux.HandleFunc("/",func(w http.ResponseWriter,r *http.Request){if r.URL.Path!="/"{if _,err:=fs.Stat(built,strings.TrimPrefix(r.URL.Path,"/"));err!=nil{r.URL.Path="/"}};if strings.Contains(r.URL.Path,"assets/"){w.Header().Set("Cache-Control","public,max-age=31536000,immutable")}else{w.Header().Set("Cache-Control","no-cache")};files.ServeHTTP(w,r)})
 return requestMiddleware(mux)
}
func requestMiddleware(next http.Handler)http.Handler{return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){id:=r.Header.Get("X-Request-ID");if id==""{id=secureID()};w.Header().Set("X-Request-ID",id);record:=&statusWriter{ResponseWriter:w,status:http.StatusOK};start:=time.Now();next.ServeHTTP(record,r);if r.URL.Path!="/healthz"&&r.URL.Path!="/readyz"&&r.URL.Path!="/metrics"{requests.Add(1);span:=trace.SpanFromContext(r.Context()).SpanContext();slog.Info("http request","request_id",id,"trace_id",span.TraceID().String(),"span_id",span.SpanID().String(),"method",r.Method,"route",normalized(r.URL.Path),"status",record.status,"latency_ms",time.Since(start).Milliseconds(),"application",%q,"namespace",value("STEADYSTATE_APP_NAMESPACE","local"),"version",value("STEADYSTATE_APP_VERSION","development"))}})}
func secureID()string{value:=make([]byte,16);if _,err:=rand.Read(value);err!=nil{return strconv.FormatInt(time.Now().UnixNano(),16)};return hex.EncodeToString(value)}
func normalized(path string)string{if strings.HasPrefix(path,"/api/"){return "/api/*"};return path}
func value(key,fallback string)string{if v:=os.Getenv(key);v!=""{return v};return fallback}
func configureTracing(ctx context.Context)(func(context.Context)error,error){
 otel.SetTextMapPropagator(propagation.NewCompositeTextMapPropagator(propagation.TraceContext{},propagation.Baggage{}));endpoint:=os.Getenv("OTEL_EXPORTER_OTLP_ENDPOINT");if endpoint==""{return func(context.Context)error{return nil},nil}
 exporter,err:=otlptracegrpc.New(ctx,otlptracegrpc.WithEndpoint(endpoint),otlptracegrpc.WithInsecure());if err!=nil{return nil,err}
 platformResource,err:=resource.New(ctx,resource.WithAttributes(attribute.String("service.name",%q),attribute.String("service.namespace",value("STEADYSTATE_APP_NAMESPACE","local")),attribute.String("service.version",value("STEADYSTATE_APP_VERSION","development")),attribute.String("steadystate.application",%q)));if err!=nil{return nil,err}
 provider:=sdktrace.NewTracerProvider(sdktrace.WithBatcher(exporter),sdktrace.WithResource(platformResource));otel.SetTracerProvider(provider);return provider.Shutdown,nil
}
`, proxyTarget, name, name, name, name, name, name)
}
